name: grown
version: 1.3.6
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  shared_preferences: ^2.1.2
  percent_indicator: 4.2.3
  google_fonts: ^6.1.0
  fluttertoast: ^8.2.2
  image_cropper: ^5.0.0
  path_provider: ^2.0.15
  image_picker: ^1.0.0
  connectivity_plus: ^5.0.1
  image: ^4.0.17
  pdf: ^3.10.4
  async: any
  http: ^1.1.0
  date_time_picker: any
  persistent_bottom_nav_bar: 5.0.2
  flutter_launcher_icons: 0.13.1
  camera: ^0.10.5+5
  permission_handler: ^11.0.1
  shimmer: 3.0.0
  animated_splash_screen: 1.3.0
  page_transition: ^2.1.0
  jwt_decoder: 2.0.1
  url_launcher: ^6.2.0
  flutter_email_sender: ^6.0.2
  dart_jsonwebtoken: any
  flutter_image_compress: ^2.1.0
  photo_view: 0.14.0
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4
  overlay_support: 2.1.0
  flutter_local_notifications: ^16.1.0
  flutter_native_timezone: 2.0.0
  welltested: ^2.0.0-preview.1
  syncfusion_flutter_charts: any
  package_info_plus: ^4.2.0
  infinite_scroll_pagination: ^4.0.0
  file_selector: ^1.0.0
  file_picker: ^6.0.0
  csv: ^5.0.2
  excel: ^2.1.0
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter_launcher_icons: 
  android: launcher_icon
  image_path: assets/images/grown_logo.png
  ios: true
  min_sdk_android: 21

flutter: 
  assets: 
    - assets/images/
    - assets/lottie/
  uses-material-design: true

