// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7TEufmtntiZ_Ofj-m8OKDhD8rtyNvxH0',
    appId: '1:926588559523:web:499ddc63233010cb44df16',
    messagingSenderId: '926588559523',
    projectId: 'grown-d54b5',
    authDomain: 'grown-d54b5.firebaseapp.com',
    storageBucket: 'grown-d54b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfmskaVLJDi-ymhCJivCBJ4q868bmf8kk',
    appId: '1:926588559523:android:6e21d489fc1dba0544df16',
    messagingSenderId: '926588559523',
    projectId: 'grown-d54b5',
    storageBucket: 'grown-d54b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0a0pAZxFRGiMG72o72ip5QqhqzEyvgaU',
    appId: '1:926588559523:ios:ff3975dce9e4ad0844df16',
    messagingSenderId: '926588559523',
    projectId: 'grown-d54b5',
    storageBucket: 'grown-d54b5.appspot.com',
    iosClientId: '926588559523-hmctbqljel83feigqbvqjmmrcljbmr0g.apps.googleusercontent.com',
    iosBundleId: 'com.grown.grown',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0a0pAZxFRGiMG72o72ip5QqhqzEyvgaU',
    appId: '1:926588559523:ios:ff3975dce9e4ad0844df16',
    messagingSenderId: '926588559523',
    projectId: 'grown-d54b5',
    storageBucket: 'grown-d54b5.appspot.com',
    iosClientId: '926588559523-hmctbqljel83feigqbvqjmmrcljbmr0g.apps.googleusercontent.com',
    iosBundleId: 'com.grown.grown',
  );
}
